/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriel
 */
public class MainView extends javax.swing.JFrame {
    
    private Controller controller; 
    //Nombre del cuadro de dialogo que se muestra al ejecutar el main
    private String appName;
    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        appName="Deepspace";
        this.setTitle(appName);
        showView();
        
        inputView1.mw = this;
    }
    
    public void updateView(){
        stackView.updateView();
    }
    
    public void setController(Controller c){
        controller = c;
    }
    
    public void recibeInput(String s){
        System.out.print(s);
        controller.inputHandler(s);
        this.updateView();
    }
    
    public void addToStack(String num){
        stackView.addNum(num);
    }
    
    public void removeFromStack(){
        stackView.removeNum();
    }
    
    public void cleanStack(){
        stackView.clean();
    }
    
    public void setVar(int i, String num){
        varView.setVariable(i, num);
    }
    
    public void setVar(char c, String num){
        varView.setVariable(c, num);
    }
    
    private void showView(){
        this.setVisible(true);
    }
    
    //Obtiene el nombre de la aplicación
    public String getAppName(){
        return appName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputView1 = new View.InputView();
        varView = new View.VariablesView();
        stackView = new View.StackView();
        infoView1 = new View.InfoView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(varView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stackView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(infoView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stackView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void InputErrorMessage(){
        JOptionPane.showMessageDialog(this, "", getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    public void NoValueInStackToOperateMessage(){
        JOptionPane.showMessageDialog(this, "", getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    public void NoValueInVarToOperateMessage(){
        JOptionPane.showMessageDialog(this, "", getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    public void CantDivideByZeroMessage(){
        JOptionPane.showMessageDialog(this, "", getAppName(), JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.InfoView infoView1;
    private View.InputView inputView1;
    private View.StackView stackView;
    private View.VariablesView varView;
    // End of variables declaration//GEN-END:variables
}
