/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author gabriel
 */
public class VarView extends javax.swing.JPanel {
    
    /**
     * Creates new form StackView
     */
    public VarView() {
        initComponents();
        //DEBUG
        System.out.print(this.getComponents());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stack11 = new javax.swing.JLabel();
        stack10 = new javax.swing.JLabel();
        stack9 = new javax.swing.JLabel();
        stack8 = new javax.swing.JLabel();
        stack7 = new javax.swing.JLabel();
        stack6 = new javax.swing.JLabel();
        stack5 = new javax.swing.JLabel();
        stack3 = new javax.swing.JLabel();
        stack4 = new javax.swing.JLabel();
        stack2 = new javax.swing.JLabel();
        satck1 = new javax.swing.JLabel();
        stack0 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        stack12 = new javax.swing.JLabel();
        stack13 = new javax.swing.JLabel();
        stack14 = new javax.swing.JLabel();
        stack15 = new javax.swing.JLabel();
        stack16 = new javax.swing.JLabel();
        stack17 = new javax.swing.JLabel();
        satck2 = new javax.swing.JLabel();
        stack1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        stack18 = new javax.swing.JLabel();
        stack19 = new javax.swing.JLabel();
        stack20 = new javax.swing.JLabel();
        stack21 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        stack22 = new javax.swing.JLabel();
        stack23 = new javax.swing.JLabel();

        stack11.setText("jLabel1");

        stack10.setText("jLabel1");

        stack9.setText("jLabel1");

        stack8.setText("jLabel1");

        stack7.setText("jLabel1");

        stack6.setText("jLabel1");

        stack5.setText("jLabel1");

        stack3.setText("jLabel1");

        stack4.setText("jLabel1");

        stack2.setText("jLabel1");

        satck1.setText("jLabel1");

        stack0.setText("jLabel1");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        stack12.setText("jLabel1");

        stack13.setText("jLabel1");

        stack14.setText("jLabel1");

        stack15.setText("jLabel1");

        stack16.setText("jLabel1");

        stack17.setText("jLabel1");

        satck2.setText("jLabel1");

        stack1.setText("jLabel1");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        stack18.setText("jLabel1");

        stack19.setText("jLabel1");

        stack20.setText("jLabel1");

        stack21.setText("jLabel1");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        stack22.setText("jLabel1");

        stack23.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stack6)
                    .addComponent(stack7)
                    .addComponent(stack8)
                    .addComponent(stack9)
                    .addComponent(stack10)
                    .addComponent(stack11)
                    .addComponent(stack22))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stack5)
                    .addComponent(stack4)
                    .addComponent(stack3)
                    .addComponent(stack2)
                    .addComponent(satck1)
                    .addComponent(stack0)
                    .addComponent(stack23))
                .addGap(19, 19, 19)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stack13)
                    .addComponent(stack12)
                    .addComponent(stack21)
                    .addComponent(stack20)
                    .addComponent(stack19)
                    .addComponent(stack18))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stack14)
                    .addComponent(stack16)
                    .addComponent(stack15)
                    .addComponent(stack17)
                    .addComponent(satck2)
                    .addComponent(stack1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack14)
                            .addComponent(stack18))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack16)
                            .addComponent(stack19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack15)
                            .addComponent(stack20))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack17)
                            .addComponent(stack21))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(satck2)
                            .addComponent(stack12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack1)
                            .addComponent(stack13))
                        .addGap(37, 37, 37))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack5)
                            .addComponent(stack11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack4)
                            .addComponent(stack10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack3)
                            .addComponent(stack9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack2)
                            .addComponent(stack8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(satck1)
                            .addComponent(stack7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stack0)
                            .addComponent(stack6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stack22)
                            .addComponent(stack23))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator3)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel satck1;
    private javax.swing.JLabel satck2;
    private javax.swing.JLabel stack0;
    private javax.swing.JLabel stack1;
    private javax.swing.JLabel stack10;
    private javax.swing.JLabel stack11;
    private javax.swing.JLabel stack12;
    private javax.swing.JLabel stack13;
    private javax.swing.JLabel stack14;
    private javax.swing.JLabel stack15;
    private javax.swing.JLabel stack16;
    private javax.swing.JLabel stack17;
    private javax.swing.JLabel stack18;
    private javax.swing.JLabel stack19;
    private javax.swing.JLabel stack2;
    private javax.swing.JLabel stack20;
    private javax.swing.JLabel stack21;
    private javax.swing.JLabel stack22;
    private javax.swing.JLabel stack23;
    private javax.swing.JLabel stack3;
    private javax.swing.JLabel stack4;
    private javax.swing.JLabel stack5;
    private javax.swing.JLabel stack6;
    private javax.swing.JLabel stack7;
    private javax.swing.JLabel stack8;
    private javax.swing.JLabel stack9;
    // End of variables declaration//GEN-END:variables
}
